version: '3.8'

services:
  url-shortener:
    build: ./
    command: ./app -postgres=false
    ports:
      - "4000:4000"

  url-shortener-db:
    build: ./
    command: ./wait-for-postgres.sh db ./app -postgres=true
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_PASSWORD: postgres
  db:
    restart: always
    image: postgres:14.4-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./schema/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"